title: <p align="center"> Nivetha </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/nivetha-sri-7262367a/">LinkedIn</a> |
  <a href="https://github.com/NivethaSri">GitHub</a>
  
  <br>   
  i'm working as a Teachnical Lead with 10 years of experience. Worked in iOS, iPadOS,macOS applications.
  <br>
  </p>



theme: jekyll-theme-minimal
